### PR TITLE
Solve `yip` does not work on `pip` 10 issue

### PR DESCRIPTION
**Pull request by singularitti**
This pull request is dedicated to solve issue #8.

### CODE REVIEW

**Comment by qwhex** [comment]
Thanks, looks good to me.

**Comment by singularitti** [comment]
Glad to see this PR has been merged. But it seems that the [PYPI package](https://pypi.org/project/yip/) was not updated. Could you please update the PYPI? @qwhex Thanks!

**Comment by qwhex** [comment]
@balzss ping

**Comment by kiloforce** [comment]
If issue #17 is eventually resolved, the PyPI package should be updated.

**Pull request merged**
